sass:
  style: compressed
baseurl: /blog
highlighter: rouge
gems:
  - 'jekyll-mentions'
description: 'Haroen Viaene is a student electronics-informatics in Ghent, living in Bruges. Interested in web development, space and travelling.'