sass:
  style: compressed
permalink: :title
highlighter: rouge
markdown: kramdown
future: true
kramdown:
  input: GFM
  footnote_backlink: '&#8617;&#xfe0e;'
gems:
  - 'jekyll-mentions'
  - 'jekyll-redirect-from'
description: 'Haroen Viaene is a student electronics-informatics in Ghent, living in Bruges (Belgium). Interested in web development, space and travelling.'
url: https://blog.haroen.me
# url: http://localhost:4000
