sass:
  style: compressed
permalink: :title
highlighter: pygments
markdown: kramdown
kramdown:
  input: GFM
gems:
  - 'jekyll-mentions'
  - 'jekyll-redirect-from'
description: 'Haroen Viaene is a student electronics-informatics in Ghent, living in Bruges. Interested in web development, space and travelling.'