sass:
  style: compressed
baseurl: /blog
permalink: :title
highlighter: pygments
gems:
  - 'jekyll-mentions'
description: 'Haroen Viaene is a student electronics-informatics in Ghent, living in Bruges. Interested in web development, space and travelling.'